config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("finance.urls")),
    path('accounts/', include('allauth.urls')),
]

finance/urls.py
from django.urls import path
from . import views

app_name    = "finance"
urlpatterns = [
    path('', views.index, name="index"),
    path('category',views.category,name="category"),
    path('category_edit/<int:pk>', views.category_edit, name="category_edit"),
    path('category_delete/<int:pk>', views.category_delete, name="category_delete"),
    path('balance_delete/<int:pk>', views.balance_delete, name="balance_delete"),
]

finance/models.py
from django.db import models
from django.utils import timezone

from django.contrib.auth.models import User

class Category(models.Model):

    class Meta:
        db_table = "category"

        #複合ユニーク制約に仕立てることで、同じ投稿者が、同じカテゴリ名で同じ収支フラグを指定することはできないようにさせる。
        # 参照:https://noauto-nolife.com/post/django-same-user-operate-prevent/
        #値はタプルでもリストでもよい。

        unique_together = ["name","income","user"]


    name    = models.CharField(verbose_name="カテゴリ名",max_length=20)
    income  = models.BooleanField(verbose_name="収入フラグ",default=False)
    user    = models.ForeignKey(User, verbose_name="投稿者", on_delete=models.CASCADE, null=True,blank=True)

    def __str__(self):
        return self.name

class Balance(models.Model):

    class Meta:
        db_table = "balance"

    dt          = models.DateTimeField(verbose_name="投稿日時",default=timezone.now)
    pay_date    = models.DateField(verbose_name="決済日")
    category    = models.ForeignKey(Category,verbose_name="カテゴリ",on_delete=models.CASCADE)
    value       = models.IntegerField(verbose_name="金額") 
    user        = models.ForeignKey(User, verbose_name="投稿者", on_delete=models.CASCADE, null=True,blank=True)

    def __str__(self):
        return self.category.name

finance/forms.py
from django import forms 
from django.core.validators import MinValueValidator,MaxValueValidator

from .models import Category,Balance

class BalanceForm(forms.ModelForm):

    class Meta:
        model   = Balance
        fields  = [ "category","pay_date","value","user" ]

class CategoryForm(forms.ModelForm):

    class Meta:
        model   = Category
        fields  = [ "name","income","user" ]
        error_messages = { 
            'comment': {
                'max_length': "これで実現できます",
                'required': "文字列入力してください",
            },
        }


#モデルを継承しないフォームクラス
class YearMonthForm(forms.Form):
    year    = forms.IntegerField()
    month   = forms.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(12)])

finance/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View

from django.db.models.functions import TruncMonth
from django.db.models import Count,Sum


from .models import Category,Balance
from .forms import CategoryForm,BalanceForm,YearMonthForm

import datetime


#↓追加
from django.contrib import messages



class IndexView(LoginRequiredMixin,View):
    
    #日ごとの収支計算し返却する。
    def calc(self, balances):

        today       = ""
        before_day  = ""

        day_balances = []
        dic         = { "day":"","income":0,"spending":0 }

        for balance in balances:
            today   = str(balance.pay_date.day)

            #前回のループと日付不一致の時、アペンドして新規作成
            if today != before_day:

                #初期状態ではない場合のみアペンド
                if dic["day"] != "":
                    day_balances.append(dic)

                dic         = { "day":"","income":0,"spending":0 }
                dic["day"]  = today

            if balance.category.income:
                dic["income"] += balance.value
            else:
                dic["spending"] += balance.value

            before_day  = today

        day_balances.append(dic)
        print(day_balances)

        return day_balances

    def get(self, request, *args, **kwargs):

        context     = {}
        context["categories"]  = Category.objects.filter(user=request.user.id).order_by("income")

        form    = YearMonthForm(request.GET)

        cleaned_month   = None
        cleaned_year    = None

        #指定された年月のデータを取得。指定がない・誤りがある場合は今月のデータを取得。
        if form.is_valid():
            cleaned_data    = form.clean()

            print(cleaned_data["month"])
            print(cleaned_data["year"])

            cleaned_month   = cleaned_data["month"]
            cleaned_year    = cleaned_data["year"]

            dt  = datetime.datetime(year=cleaned_data["year"],month=cleaned_data["month"],day=1)

            context["balances"]     = Balance.objects.filter(pay_date__year=cleaned_data["year"],pay_date__month=cleaned_data["month"],user=request.user.id).order_by("pay_date")

        else:
            #今月の初日を手に入れる。
            dt  = datetime.datetime.now()
            dt  = dt.replace(day=1)

            context["balances"]     = Balance.objects.filter(pay_date__year=dt.year,pay_date__month=dt.month,user=request.user.id).order_by("pay_date")

        #TODO:このinit_dtは書き換えしない
        init_dt = dt

        #最新と最古のデータを取得
        oldest_balance  = Balance.objects.order_by("pay_date").first()
        newest_balance  = Balance.objects.order_by("-pay_date").first()

        #ここで存在していれば最古と最新の日付を入手。無い場合はそれぞれ今日の日付を指定
        if oldest_balance:
            oldest_pay_date   = oldest_balance.pay_date
        else:
            oldest_pay_date   = datetime.date.today()

        if newest_balance:
            newest_pay_date   = newest_balance.pay_date
        else:
            newest_pay_date   = datetime.date.today()

        #年リストを作り、Selectタグを作る。
        year_list   = []

        oldest_year = oldest_pay_date.year
        newest_year = newest_pay_date.year

        if cleaned_year != None:
            if cleaned_year <= oldest_pay_date.year:
                oldest_year = cleaned_year
            elif newest_pay_date.year <= cleaned_year:
                newest_year = cleaned_year


        """
        for i in range(oldest_year,newest_year+1,1):
            year_list.append(i)
        """
        #年表示新しい順
        for i in range(newest_year,oldest_year-1,-1):
            year_list.append(i)


        context["year_list"]    = year_list
        context["month"]        = dt.month
        context["year"]         = dt.year

        print(oldest_pay_date)
        print(newest_pay_date)

        #カレンダーに合わせ、日ごとの収支を計算する
        day_balances    = self.calc(context["balances"])

        #今月を手に入れる
        month       = dt.month

        #month_dateはweek_dateのリスト、week_dateは日付のリスト
        month_date  = []
        week_date   = []

        #最終的に作られるmonth_dateのイメージ。このように複数のweek_dateを含む。月の最初が日曜日ではない場合、必要な数だけ空欄をアペンドしておく
        """
        [ ['  ', '  ', '1 ', '2 ', '3 ', '4 ', '5 '],
          ['6 ', '7 ', '8 ', '9 ', '10', '11', '12'],
          ['13', '14', '15', '16', '17', '18', '19'],
          ['20', '21', '22', '23', '24', '25', '26'],
          ['27', '28', '29', '30']
          ]

          [ {"dt":'6 ',"income":3000,"spending":600 }, '7 ', '8 ', '9 ', '10', '11', '12'],
        """

        #一日ずつずらしてweek_dateにアペンドする。
        #datetimeのオブジェクトは .weekday() で数値化した曜日が出力される(月曜日が0、日曜日が6)

        #日曜日以外の場合、空欄を追加する。
        if dt.weekday() != 6:
            for i in range(dt.weekday()+1):
                week_date.append("")

        #1日ずつ追加して月が変わったらループ終了
        while month == dt.month:
            
            #TODO:ここで辞書型をアペンド(日付、収入の合計、支出の合計)
            dic = {"day":str(dt.day),"income":0,"spending":0 }

            flag    = False
            for day_balance in day_balances:
                if dic["day"] == day_balance["day"]:
                    week_date.append(day_balance)
                    flag    = True
                    break

            if not flag:
                week_date.append(dic)

            #1日追加する
            dt  = dt + datetime.timedelta(days=1)

            #週末になるたびに追加する。
            if dt.weekday() == 6:
                month_date.append(week_date)
                week_date   = []

        #一ヶ月の最終週を追加する。
        if dt.weekday() != 6:
            month_date.append(week_date)

        context["month_date"]   = month_date


        #TODO:カテゴリごとのデータを集計する。

        #まずアクセスしたユーザーのカテゴリを取得。
        categories  = Category.objects.filter(user=request.user.id).order_by("income")
        

        category_of_balances    = []

        #カテゴリごとの計算(投稿者であり、指定した年月で絞り込む)
        for category in categories:
            print(init_dt.year)
            print(init_dt.month)
            balances    = Balance.objects.filter(pay_date__year=init_dt.year, pay_date__month=init_dt.month, user=request.user.id, category=category.id)

            total       = 0
            for balance in balances:
                total += balance.value
            
            dic = {}
            dic["income"]   = category.income
            dic["category"] = category.name
            dic["total"]    = total

            data            = dic.copy()
            category_of_balances.append(data)

        context["category_of_balances"] = category_of_balances


        context["monthly_income"]   = Balance.objects.filter(user=request.user.id,category__income=True).annotate(date=TruncMonth("pay_date")).values("date").annotate(count=Count("id"),amount=Sum("value")).values("date","amount", "count").order_by("-date")
        context["monthly_spending"] = Balance.objects.filter(user=request.user.id,category__income=False).annotate(date=TruncMonth("pay_date")).values("date").annotate(count=Count("id"),amount=Sum("value")).values("date","amount", "count").order_by("-date")


        
        #TODO:今月の支出と収入を計算する(今月の自分が投稿したデータで、.aggregate()とSumを使用することで、指定したフィールドの合計値を算出できる。)

        this_month_income = Balance.objects.filter(user=request.user.id, category__income=True, pay_date__year=init_dt.year, pay_date__month=init_dt.month).aggregate(Sum("value"))
        context["this_month_income"] = this_month_income["value__sum"]
        

        this_month_spending = Balance.objects.filter(user=request.user.id, category__income=False, pay_date__year=init_dt.year, pay_date__month=init_dt.month).aggregate(Sum("value"))
        context["this_month_spending"] = this_month_spending["value__sum"]


        this_year_income = Balance.objects.filter(user=request.user.id, category__income=True, pay_date__year=init_dt.year).aggregate(Sum("value"))
        this_year_spending = Balance.objects.filter(user=request.user.id, category__income=False, pay_date__year=init_dt.year).aggregate(Sum("value"))

        #Noneであるにもかかわらず演算をしている。
        if not this_year_income["value__sum"]:
            this_year_income["value__sum"] = 0
            
        if not this_year_spending["value__sum"]:
            this_year_spending["value__sum"] = 0

        print( init_dt.year , "年の収支は", this_year_income["value__sum"] - this_year_spending["value__sum"] ,"円です。")



        month_list  = []
        for i in range(1,13):
            this_month_income = Balance.objects.filter(user=request.user.id, category__income=True, pay_date__year=init_dt.year, pay_date__month=i).aggregate(Sum("value"))
            this_month_spending = Balance.objects.filter(user=request.user.id, category__income=False, pay_date__year=init_dt.year, pay_date__month=i).aggregate(Sum("value"))

            if not this_month_income["value__sum"]:
                this_month_income["value__sum"] = 0
                
            if not this_month_spending["value__sum"]:
                this_month_spending["value__sum"] = 0

            dic = {}
            dic["month"]    = str(i)
            dic["value"]    = this_month_income["value__sum"] - this_month_spending["value__sum"]
            month_list.append(dic)

        print(month_list)

        context["month_list"] = month_list


        income_all_sum = Balance.objects.filter(user=request.user.id,category__income=True).aggregate(Sum("value"))
        spending_all_sum = Balance.objects.filter(user=request.user.id,category__income=False).aggregate(Sum("value"))

        #Noneであるにもかかわらず演算をしている。
        if not income_all_sum["value__sum"]:
            income_all_sum["value__sum"] = 0
                    
        if not spending_all_sum["value__sum"]:
            spending_all_sum["value__sum"] = 0

        print(income_all_sum["value__sum"] - spending_all_sum["value__sum"])

        context["income_all_sum"]  =  income_all_sum
        context["spending_all_sum"]  =  spending_all_sum
        context["all_sum"]  =  income_all_sum["value__sum"] - spending_all_sum["value__sum"]



        #先月と来月のリンクを作る
        if init_dt.month == 12: 

templates/finance/calender.html
{% load humanize %}
<!--カレンダー-->
<div class="mx-5 year_month_select">
    <form action="" method="GET">
        <div class="d-flex p-1 bd-highlight" >

            <a class="calender_month_link" href="{{ prev_month }}"><i class="fas fa-chevron-left"></i></a>

            <select class="mr-3 custom-select" name="year">
                {% for y in year_list %}
                <option value="{{ y }}" {% if y == year %}selected{% endif %}>{{ y }}</option>
                {% endfor %}
            </select>
                    
            <select class="mr-3 custom-select"  name="month">
                <option value="1"  {% if month == 1 %}selected{% endif %}>1</option>
                <option value="2"  {% if month == 2 %}selected{% endif %}>2</option>
                <option value="3"  {% if month == 3 %}selected{% endif %}>3</option>
                <option value="4"  {% if month == 4 %}selected{% endif %}>4</option>
                <option value="5"  {% if month == 5 %}selected{% endif %}>5</option>
                <option value="6"  {% if month == 6 %}selected{% endif %}>6</option>
                <option value="7"  {% if month == 7 %}selected{% endif %}>7</option>
                <option value="8"  {% if month == 8 %}selected{% endif %}>8</option>
                <option value="9"  {% if month == 9 %}selected{% endif %}>9</option>
                <option value="10" {% if month == 10 %}selected{% endif %}>10</option>
                <option value="11" {% if month == 11 %}selected{% endif %}>11</option>
                <option value="12" {% if month == 12 %}selected{% endif %}>12</option>
            </select>
        
            <input class="btn btn-success" type="submit" value="検索">

            <a class="calender_month_link" href="{{ next_month }}"><i class="fas fa-chevron-right"></i></a>

        </div>
    </form>

    <div class="free">
        <div class="text-center free-money "><i class="fas fa-hand-holding-usd"></i>自由に使えるお金:<div id="free">{{ all_sum|default:"0"|intcomma }}</div>円</div>
        <input class="btn-outline-info hide-visible visible" type="button" value="表示"  onclick="document.getElementById('free').style.visibility = 'visible';">
        <input class="btn-outline-info hide-visible hide" type="button" value="非表示" onclick="document.getElementById('free').style.visibility = 'hidden';">
    </div>
</div>




<div class="table-responsive">
    <table class="calender " style="border-radius: 2rem;">
        <thead>
            <tr class="calender_head">
                <td>日</td>
                <td>月</td>
                <td>火</td>
                <td>水</td>
                <td>木</td>
                <td>金</td>
                <td>土</td>
            </tr>
        </thead>
        <tbody>
            {% for week_date in month_date %}
            <tr>
                {% for day in week_date %}
                <td>
                    <div class="day_cell">
                        <div>{{ day.day }}</div>
                        <!--chart.jsで読み取れるよう。ここに収支を意味するクラス名をセット-->
                        <div class="day_detail">{{ day.income|default:""|intcomma   }}</div>
                        <div class="day_detail">{{ day.spending|default:""|intcomma }}</div>
                    </div>
                    <!--TODO:収入と支出で色を分ける-->
                    <div class="day_cell_small">
                        <div class="day_cell_small_inner"><div class="day_detail_mark {% if day.income   %}day_detail_mark_income{% endif %}"></div>  </div>
                        <div class="day_cell_small_inner"><div class="day_detail_mark {% if day.spending %}day_detail_mark_spending{% endif %}"></div></div>
                    </div>
                </td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>

<div class="month_balance">
    <div class="month_balance_result">{{ year }}年{{ month }}月</div>    
    <div class="month_balance_result">収入:{{ this_month_income|default:"0"|intcomma }}円</div>
    <div class="month_balance_result">支出:{{ this_month_spending|default:"0"|intcomma }}円</div>
</div>

templates/finance/index.html
{% load static %}
{% load humanize %}


<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
	<title>Easy Finance</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


    <!--fontawesome-->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <!--日本語化用JS-->
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ja.js"></script>

    <!--jQueryの読み込み-->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

    <!--chart.js CDN-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.6.2/dist/chart.min.js"></script>
    <script src="{% static 'finance/js/chart.js' %}"></script>

    <link rel="stylesheet" href="{% static 'finance/css/style.css' %}">
    <script src="{% static 'finance/js/script.js' %}"></script>

</head>
<body>
    
    <!--ここに家計簿のタイトルを-->
    <header class="header_area">
        <a class="header_link" href="{% url 'account_logout' %}"><i class="fas fa-sign-out-alt"></i><div class="logout">logout</div></a>
        <h1 class="header_title" ><i class="far fa-calendar-alt"></i> Easy Finance</h1>
    </header>
    
     <!--
        Djangoメッセージフレームワーク
        https://docs.djangoproject.com/en/3.2/ref/contrib/messages/#using-messages-in-views-and-templates
    -->

    {% for message in messages %}
    <div class="message message_{{ message.tags }}">
        <div class="message_content">{{ message }}</div>       
        <div class="message_delete"><i class="fas fa-times"></i></div>
    </div>
    {% endfor %}


    <div class="row mx-0">
        <div class="col-md-6">{% include "finance/calender.html" %}</div>
        <div class="col-md-6">{% include "finance/list.html" %}</div>
    </div>

</body>

</html>

templates/finance/list.html
{% load humanize %}

<div class="balance_form_area">
    <h2><i class="fas fa-pen"></i>収支入力フォーム</h2>

    <form action="" method="POST">
        {% csrf_token %}
        <select class="form-control" name="category">
            {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}({% if category.income %}収入{% else %}支出{% endif %})</option>
            {% endfor %}
        </select>
        <div class="form-row my-2">
            <div class="col-sm-6">
                <label>決済日</label>
                <input class="form-control" type="text" name="pay_date" readonly placeholder="決済日を入力してください">
            </div>
            <div class="col-sm-6">
                <label>金額</label>
                <input class="form-control" type="number" name="value" value="0">
            </div>
        </div>
        <input class="btn btn-primary form-control" type="submit" value="保存">
    </form>
</div>


<div class='tabs'>
    <div class='tab-buttons'>
        <span class='content1'>月収支一覧</span>
        <span class='content2'>カテゴリ追加</span>
        <span class='content3'>登録カテゴリ</span>
        <span class='content4'>カテゴリ別</span>
        <span class='content5'><i class="fas fa-chart-pie"></i>今月の収支</span>
        <span class='content6'><i class="far fa-chart-bar"></i>今年の収支</span>
        <div id='lamp' class='content1'></div>
    </div>
    <div class='tab-content'>   
        <div class='content1'>
            <table class="table table-striped table-bordered my-1">
                <thead class="thead-dark">
                    <tr>
                        <th class="text-center">決済日</th>
                        <th class="text-center">登録日時</th>
                        <th class="text-center">カテゴリ</th>
                        <th class="text-center">金額</th>
                        <th class="text-center">削除</th>
                    </tr>
                </thead>
                <tbody>
                    {% for balance in balances %}
                    <tr>
                        <td class="text-center">{{ balance.pay_date|date:"j日" }}</td>
                        <td class="text-center">{{ balance.dt }}</td>
                        <td class="text-center">{{ balance.category.name }}</td>
                        <td class="text-right" style="{% if balance.income %}color:blue;{% else %}color:crimzon;{% endif %}">{{ balance.value|intcomma }}円</td>
                        <td class="text-center">
                            <form action="{% url 'finance:balance_delete' balance.id %}" method="POST" onsubmit="if(confirm('本当に削除しますか？')){ return true } else { return false };">
                                {% csrf_token %}
                                <input style="aline-items:center;" class="btn btn-outline-danger text-center" type="submit" value="削除">
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class='content2'>
            <div class="category_form_area">
                {% comment %} <h3 class="text-center"><i class="far fa-list-alt"></i>カテゴリ追加フォーム</h3> {% endcomment %}
            
                <form action="{% url 'finance:category' %}" method="POST">
                    {% csrf_token %}
            
                    <div class="row">
                        <div class="col"><input class="form-control category_name" type="text" name="name" placeholder="カテゴリ名"></div>
                        <div class="col"><input id="income_chk" class="income_chk" type="checkbox" name="income"><label class="income_chk_label" for="income_chk"></label></div>
                    </div>
            
                    <input class="btn btn-primary form-control" type="submit" value="追加">
                </form>
            </div>
        </div>
      
        <div class='content3'>
            <div class="category_view_area">
                <div class="category_list_area">
                    <div class="category_list_header">
                        <div class="category_list_header_content">カテゴリ名</div>
                        <div class="category_list_header_content">収支</div>
                        <div class="category_list_header_content">編集/削除</div>
                    </div>
            
                    {% for category in categories %}
                    <div>
            
                        <input id="category_chk_{{ category.id }}" class="category_chk" type="checkbox">
                        <div class="category_list_view">
                            <div class="category_list_view_content category_list_view_content_name">{{ category.name }}</div>
                            <div class="category_list_view_content">
                                {% if category.income %}
                                <span class="category_list_view_content_income">収入</span>{% else %}
                                <span class="category_list_view_content_spending">支出</span>
                                {% endif %}
                            </div>
                            <div class="category_list_view_content">
                                <label class="category_chk_label category_chk_label_start" for="category_chk_{{ category.id }}">編集</label>
                            
                                <form action="{% url 'finance:category_delete' category.id %}" method="POST" onsubmit="if(confirm('カテゴリを削除しますか？\n\n【注意】カテゴリに紐付けられている全収支データも削除されます！')){ return true } else { return false };" style="display:inline-block;">
                                    {% csrf_token %}
                                    <input class="category_chk_label category_chk_label_cancel" type="submit" value="削除">
                                </form>
            
                            </div>
                        </div>
                        <form class="category_list_edit" action="{% url 'finance:category_edit' category.id %}" method="POST">
                            {% csrf_token %}
                            <div class="category_list_edit_content"><input class="form-control" type="text" name="name" value="{{ category.name }}"></div>
                            <div class="category_list_edit_content">
                                <input id="income_chk_{{ category.id }}" class="income_chk" type="checkbox" name="income" {% if category.income %}checked{% endif %}><label class="income_chk_label" for="income_chk_{{ category.id }}"></label>
                            </div>
                            <div class="category_list_edit_content">
                                <input class="category_edit_submit" type="submit" value="編集する">
                                <label class="category_chk_label category_chk_label_cancel" for="category_chk_{{ category.id }}">キャンセル</label>
                            </div>
                        </form>
                    
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        
        <div class='content4'>
            <table class="table table-striped table-bordered my-1">
                <thead class="thead-dark">
                    <tr>
                        <th class="text-center">カテゴリ</th>
                        <th class="text-center">合計(月)</th>
                    </tr>
                </thead>
                <tbody>
                    <!--カテゴリごとの集計結果-->
                    {% for c in category_of_balances %}
                    <tr>
                        <td class="text-center {% if c.income %}income_{% else %}spending_{% endif %}category">{{ c.category }}</td>
                        <td class="{% if c.income %}income_{% else %}spending_{% endif %}total text-right">{{ c.total|intcomma }}円</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
      
        <div class='content5'>
            <div class="row">
                <div style="position:relative;width:50%;">
                    <canvas id="category_graph_income"></canvas>
                </div>
                <div style="position:relative;width:50%;">
                    <canvas id="category_graph_spending"></canvas>
                </div>
            </div>
        </div>
        <div class='content6'>
            <div class="row  m-2">
                <div style="position:relative;width:100%;">
                    <canvas id="month_list_graph"></canvas>
                </div>
            </div>
            <div class="month_list_table">
                {% for m in month_list %}
                    <div class="month_list_month">{{ m.month }}月</div>
                    <div class="month_list_value">{{ m.value|intcomma }}円</div>
                {% endfor %}
            </div>
        </div>  
</div>